nome = input("Digite seu nome completo: ")
nome_modificado = nome.replace(' ', '...')
print("Nome modificado:", nome_modificado)
nome = input("DigIte o seu nome completo: ")
nome_modificado = nome.replace(' ', '...')
print("Nome modificado:", nome_modificado)